name: .NET + Appium CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    # Install and run Appium in the background
    - name: Install and Run Appium
      run: |
        npm install -g appium
        appium --version
        appium &

    # Restore dependencies in the HolyQuran directory
    - name: Restore dependencies
      run: dotnet restore
      working-directory: HolyQuran

    # Build the project in the HolyQuran directory
    - name: Build
      run: dotnet build --no-restore
      working-directory: HolyQuran

    # Run tests in the HolyQuran directory
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: HolyQuran
