name: .NET + Appium CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        api-level: [26, 27, 28]  # Modify as needed for different API levels
        target: [default]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Appium
      run: npm install -g appium

    # Verify that the real device is connected
    - name: Verify Connected Devices
      run: adb devices

    - name: Install UIAutomator2 Driver
      run: appium driver install uiautomator2

    - name: Run Appium Server
      run: |
        chmod +x ./Scripts/RunAppiumServer.sh  # Ensure the script is executable
        ./Scripts/RunAppiumServer.sh &

    - name: Wait for Appium
      run: sleep 30  # Increased wait time for Appium server

    # Restore dependencies in the HolyQuran directory
    - name: Restore dependencies
      run: dotnet restore --verbosity detailed
      working-directory: HolyQuran

    # Build the project in the HolyQuran directory
    - name: Build
      run: dotnet build --no-restore --verbosity detailed
      working-directory: HolyQuran

    # Run tests in the HolyQuran directory
    - name: Test
      run: dotnet test --no-build --verbosity detailed
      working-directory: HolyQuran
